### ISSUE TITLE
Where is the DeviceDetector.NET.NetCore source code?

### ISSUE THREAD

**Issue by hugoqribeiro** [totpero/DeviceDetector.NET#15]
Hi.

I am using the DeviceDetector.NET.NetCore package and I think I found an issue with concurrency.
Where is the source code and where can I open a issue for this problem?

Thanks in advance.

**Comment by hugoqribeiro** [comment]
Hi. Any news on this one?

**Comment by atifield** [comment]
Hello, the netcore package is a fork from another dev: https://github.com/matomo-org/device-detector

**Comment by hugoqribeiro** [comment]
Sorry. I didn't understand that.

**Comment by hugoqribeiro** [comment]
Sorry nut there is something wrong here. If I go to the repo mentioned (https://github.com/matomo-org/device-detector) there's the php version.
In NuGet, on the .NET Core package (https://www.nuget.org/packages/DeviceDetector.NET.NetCore/), the "Project Site" link points here (https://github.com/totpero/DeviceDetector.NET).

So where can I find the source code? I would like to contribute... :)
