### ISSUE TITLE
Error: {"Could not find a part of the path 'C:\\Program Files (x86)\\IIS Express\\regexes\\client\\feed_readers.yml'."}

### ISSUE THREAD

**Issue by Cloudmersive** [totpero/DeviceDetector.NET#16]
Am getting this error on a basic app:

{"Could not find a part of the path 'C:\\Program Files (x86)\\IIS Express\\regexes\\client\\feed_readers.yml'."}

Any idea why this is happening?

**Comment by gianfrancolombardo** [comment]
Hi Cloudmersive. 
You must define absolute path to DeviceDetector to find Regexes folder, before to create DeviceDetector object

For example:
`DeviceDetectorSettings.RegexesDirectory = "c:/YourProject/bin";`

or
`DeviceDetectorSettings.RegexesDirectory = WebConfigurationManager.AppSettings["RegexUserAgent"];`

Regards
