### ISSUE TITLE
Sign DLLs

### ISSUE THREAD

**Issue by PoinZ91** [totpero/DeviceDetector.NET#2]
Hello,

We would like to use DeviceDetector.NET, but we need a signed DLL.
Is it possible to sign your DLLs and resubmit them on Nuget?

Thank You.

**Comment by totpero** [comment]
Hi,
 I have published new nuget version [3.9.2.1](https://www.nuget.org/packages/DeviceDetector.NET/3.9.2.1)
Update to last version and see if is OK.

**Comment by PoinZ91** [comment]
Thank you for the quick reply. It Works :)
