### ISSUE TITLE
value cannot be null

### ISSUE THREAD

**Issue by deRightDirection** [totpero/DeviceDetector.NET#21]
I have the following code but it does not run:

var osp = new OperatingSystemParser();
                var result = osp.Parse();
                var x = result.Success;

at osp.Parse() it comes with "value cannot be null" (ArgumentNullException)

**Comment by totpero** [comment]
Hi @deRightDirection where did you set the UserAgent?
Before parse you need to set the user agent like this: `osp.SetUserAgent(userAgent);`

**Comment by deRightDirection** [comment]
Hello,

thanks for you reply, i think i completely not understand how this library works. Because I fill in an user agent string but than it will always parse the same user agent string. 

I want to check out the system on which the code is running, how do I get the information about this system? Any code examples for this, I think stupidly basic feature?
