### ISSUE TITLE
Not detecting Tablet|IPad or IsMobile does not detect IPhone

### ISSUE THREAD

**Issue by sremiger1** [totpero/DeviceDetector.NET#22]
```
DeviceDetector dd = new DeviceDetector(userAgent);
return dd.IsTablet();

 DeviceDetector dd = new DeviceDetector(userAgent);
return dd.IsMobile();

```
This does not detect the IPAD Air 2 with Safari
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15

The IsMobile does not detect IPhone 7 Software 12.4.1  Safari 13
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15

**Comment by AgileFlexAgency** [comment]
**DeviceDetector.NET/regexes/device/mobiles.yml** needs to be updated.
**DeviceDetector.NET/regexes/oss.yml** needs to be updated.

**Comment by rlarkin212** [comment]
Came across this problem today use `dd.Parse();` and then check if the device is mobile etc, should work

**Comment by totpero** [comment]
Hi @sremiger1 , is this solved?

**Comment by scottremigeraccuweather** [comment]
> Hi @sremiger1 , is this solved?

No: the device information does not change.

**Comment by totpero** [comment]
Hi @sremiger1 , @rlarkin212 , @scottremigeraccuweather, can you try with last release 4.3.0 and see if this problem persist?

**Comment by garrettlondon1** [comment]
Still persists @totpero

**Comment by totpero** [comment]
Hi @garrettlondon1, 
Can you give me some usergaents example for testig?
Or is ok this from issue?

Thaks

**Comment by garrettlondon1** [comment]
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 16_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Mobile/15E148 Safari/604.1 

- not recognized as Mobile client

**Comment by totpero** [comment]
> User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 16_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Mobile/15E148 Safari/604.1
> 
>     * not recognized as Mobile client

Hi @garrettlondon1 your problem is because you don't call `Parse` method before `IsMobile`. Look the @rlarkin212 comment.
Try like this:

```
DeviceDetector dd = new DeviceDetector(userAgent);
dd.Parse();
return dd.IsMobile();
```
Thanks for your feedback 👍

**Comment by totpero** [comment]
Hi @sremiger1 , @scottremigeraccuweather ,

For this issue:
> The IsMobile does not detect IPhone 7 Software 12.4.1 Safari 13
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15

If you try the original repo online test page this say that  `"isMobileOnlyBrowser": false` : 
https://devicedetector.lw1.at/Mozilla%2F5.0%20(Macintosh;%20Intel%20Mac%20OS%20X%2010_15)%20AppleWebKit%2F605.1.15%20(KHTML,%20like%20Gecko)%20Version%2F13.0.1%20Safari%2F605.1.15

And for this issue:
> This does not detect the IPAD Air 2 with Safari
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15

The same for this, if you look online:
https://devicedetector.lw1.at/Mozilla%2F5.0%20(Macintosh;%20Intel%20Mac%20OS%20X%2010_15)%20AppleWebKit%2F605.1.15%20(KHTML,%20like%20Gecko)%20Version%2F13.0.1%20Safari%2F605.1.15
