### ISSUE TITLE
Can´t install the nugget in my project.

### ISSUE THREAD

**Issue by rastolho** [totpero/DeviceDetector.NET#24]
I try to install the nugget in my project but i got a error, the nugget dont supporty .net framework 4.5?

**Comment by totpero** [comment]
Hi @rastolho in last release i port code to .net core, but you can install [3.11.6  version ](https://www.nuget.org/packages/DeviceDetector.NET/3.11.6) and update yaml files from path.

**Comment by totpero** [comment]
Hi @rastolho you can try last release 4.3.0, this version is supported .net framework 4.6.1
