### ISSUE TITLE
Bot Detector

### ISSUE THREAD

**Issue by buntysala** [totpero/DeviceDetector.NET#32]
Hi,

I believe this UA is a bot - _Mozilla/5.0 (Windows NT 5.1; rv:11.0) Gecko Firefox/11.0 (via ggpht.com GoogleImageProxy)_ but the library doesn't detect it as such.

**Comment by buntysala** [comment]
Did some research and it would seem that the event is related to a human opening an email.

**Comment by Findus23** [comment]
See also https://github.com/matomo-org/device-detector/issues/5359

At least the original PHP project detects this user agent as a bot: https://devicedetector.lw1.at/Mozilla%2F5.0%20(Windows%20NT%205.1;%20rv:11.0)%20Gecko%20Firefox%2F11.0%20(via%20ggpht.com%20GoogleImageProxy)
