### ISSUE TITLE
Nuget is not working

### ISSUE THREAD

**Issue by PavanRahulDandamudi** [totpero/DeviceDetector.NET#33]
I have installed DeviceDetector.NET 4.2.0 For .NET Standard 2.0 Project,But i'm unable to use it.Will it Support for .NET Standard 2.0 Project?

**Comment by emilsteen** [comment]
DeviceDetector.NET supports .NET Standard 2.0 since version 4.0.0 (July 5, 2019).

**Comment by totpero** [comment]
Hi @PavanRahulDandamudi now is supported  .NET Standard 2.0  and also .net 4.6.1 👍
