### ISSUE TITLE
NuGet release 4.2.0 not issued in GitHub

### ISSUE THREAD

**Issue by lorenzobruni** [totpero/DeviceDetector.NET#34]
Hi,

I'm about to upgrade the DeviceDetector.NET library in our project ([Issue #322 in PxStat](https://github.com/CSOIreland/PxStat/issues/322)) and I have noticed that the release 4.2.0 is available in NuGet but not in GitHub.

The latest version with the release notes I can find in GitHub is 3.11.6

Can you please issue the 4.2.0 release in GitHub as well?
It would be nice if you could add some release notes for the past 3 releases 4.0.0, 4.1.0 and 4.2.0 as well.

Thanks a mill for the great project!

![image](https://user-images.githubusercontent.com/53212047/101015403-3eff0e00-355f-11eb-9c85-ab8f89c28fa5.png)

![image](https://user-images.githubusercontent.com/53212047/101014989-9cdf2600-355e-11eb-9fbb-c930a14acb56.png)

**Comment by totpero** [comment]
👍

**Comment by totpero** [comment]
Hi @lorenzobruni  check last release v4.3.0 👍
