### ISSUE TITLE
LRU caching is not LRU caching?

### ISSUE THREAD

**Issue by emilsteen** [totpero/DeviceDetector.NET#36]
Had a quick look at the new caching implementation.

The implemented LRU (least recently used) cache looks more like a most used cache (with a hint of least recently added cache) to me. Not necessary a bad thing, but strange.

And I also think the added GenericLRUCache copied from a Github Gist has other quality issues, but I guess it works alright.

**Comment by totpero** [comment]
Hi @emilsteen ,
If you have any implementation or sugestion feel free to add.
Thanks
