### ISSUE TITLE
Path not found

### ISSUE THREAD

**Issue by Gabriella-Couto** [totpero/DeviceDetector.NET#37]
Hi!

I am using Azure Fuctions and when i am debugging the function locally my code that detects the device works, but when i publish my function it throws the following exception: Could not find a part of the path 'C:\Program Files (x86)\SiteExtensions\Functions\1.0.13154\bin\regexes\client\feed_readers.yml'.

My Code: 
            string finalString = "";
            DeviceDetector.SetVersionTruncation(VersionTruncation.VERSION_TRUNCATION_NONE);
            DeviceDetectorSettings.RegexesDirectory = System.Web.Hosting.HostingEnvironment.MapPath("~/bin/");

            var dd = new DeviceDetector(userAgent);
            dd.SetCache(new DictionaryCache());

            dd.SkipBotDetection();
            dd.Parse();

Infos: The NugetPackage DeviceDetector  is 3.11.6, my function SDK NugetPackage is 1.0.38.

**Comment by emilsteen** [comment]
The folder regexes is not published automatically for me either. You have to copy it to the server manually.

**Comment by totpero** [comment]
Try to set the yaml folder path manualy like this: DeviceDetectorSettings.RegexesDirectory = @"C:\YamlRegexsFiles\";
