### ISSUE TITLE
Path not found 'regexes\client\feed_readers.yml'

### ISSUE THREAD

**Issue by jade-octopusgroup** [totpero/DeviceDetector.NET#4]
Hi Guys,

I'm getting the following error:
System.IO.DirectoryNotFoundException: 'Could not find a part of the path 'C:\Program Files (x86)\IIS Express\regexes\client\feed_readers.yml'.'

            DeviceDetector.SetVersionTruncation(VersionTruncation.VERSION_TRUNCATION_NONE);
// Dies on this line
            DeviceDetector dd = new DeviceDetector(dto.UserAgent);
            dd.SetCache(new DictionaryCache());
            dd.SkipBotDetection();
            dd.Parse();

As no-one else has submitted an issue, it is probably my fault but I haven't a clue what it is.

Thanks,

**Comment by larswp** [comment]
i have the same issue

**Comment by totpero** [comment]
Hi,

I will try to fix this.
I think this is happen because you use DeviceDetector.NET in Web Project.
I didn't test in web project.

**Comment by silliksaar** [comment]
That is sad. A UserAgent parser that does not work for web projects! I hoped to use it but it is unusable.

**Comment by dotnetallday** [comment]
Same error for me. What a shame. Had such high hopes for this library! :(

**Comment by jade-octopusgroup** [comment]
In the absence of this solution I've been using wurfl

It has a free version with limited functionality, easily implemented and I've been using it successfully in production for a while now! Definitely worth a try.

Website: https://www.scientiamobile.com/products/wurfl-js/
Implementation: <script type="text/javascript" src="//wurfl.io/wurfl.js"></script>
Done

Good luck

**Comment by totpero** [comment]
Hi @jade-octopusgroup @larswp @silliksaar @dotnetallday I just release new update and this last version include fix for this bug and update to last version.

In web app you can set regexes path like this:
https://github.com/totpero/DeviceDetector.NET#the-default-regexes-directory-path-can-be-changed-like-this

or try this:
```csharp
DeviceDetectorSettings.RegexesDirectory = HostingEnvironment.MapPath("~/ bin");
```

**Comment by totpero** [comment]
Hi,

Was this fixed?

**Comment by jade-octopusgroup** [comment]
I've since had to move to a different service

**Comment by cwhsu1984** [comment]
This issue is not fixed yet!

**Comment by totpero** [comment]
@cwhsu1984 did you try demo web app from repo?

**Comment by cwhsu1984** [comment]
> @cwhsu1984 did you try demo web app from repo?

I already tried it on my project, and got the same error this thread mentioned.
And adding 
`DeviceDetectorSettings.RegexesDirectory = HostingEnvironment.MapPath("~/ bin");`
or 
`DeviceDetectorSettings.RegexesDirectory = HostingEnvironment.MapPath("~/bin");`
both don't work. I am not sure why the original answer has a space before 'bin'.

I am not a pro in dotnet, but there is no any explanation about what DeviceDetectorSettings.RegexesDirectory is or where it should be. 

Using code from the demo app in my project shows

> Server Error in '/' Application.
> Could not find a part of the path 'MYPRJ\bin\regexes\client\feed_readers.yml'.
> ...

As far as I know, the only thing that we have to do is install the package from NuGet and use the code from the example. Do I miss anything?

**Comment by totpero** [comment]
Try to copy this folder from [here](https://github.com/totpero/DeviceDetector.NET/tree/master/src/DeviceDetector.NET/regexes) into your location.

**Comment by cwhsu1984** [comment]
> @cwhsu1984 Try to copy this folder from [here](https://github.com/totpero/DeviceDetector.NET/tree/master/src/DeviceDetector.NET/regexes) into your location.

Alright, that works.
Say that my project directory is ProjectPath\.
I copy the `regexes` to `ProjectPath\regexes`.
Then I set the regexes directory as following:
`DeviceDetectorSettings.RegexesDirectory = HostingEnvironment.MapPath("~/");`
Then it works, but I don't think the document say anything about this.
And it's pretty strange for me when I have to copy a folder of files into my project to use a NuGet package.

**Comment by dcwirenet** [comment]
DeviceDetectorSettings.RegexesDirectory = HostingEnvironment.MapPath("~/bin");
do this 
DeviceDetectorSettings.RegexesDirectory = HostingEnvironment.MapPath("~/bin/");
this one with the forward slush worked for me

**Comment by AlexReff** [comment]
Not sure why this is closed, this project is not suited for web projects if it requires a hard path to be set and files to be copied manually to the output, completely undocumented. Will be looking for an alternative.

`Could not find a part of the path 'c:\windows\system32\inetsrv\regexes\client\feed_readers.yml'.`

**Comment by totpero** [comment]
@AlexReff this is open source project, you can contribute to create this project more better.
If you want some .net alternative, you can buy this: 
https://github.com/51Degrees/dotNET-Device-Detection
https://51degrees.com/Licencing-Pricing
