### ISSUE TITLE
NuGet-package is DEBUG-build -- should be RELEASE

### ISSUE THREAD

**Issue by gfoidl** [totpero/DeviceDetector.NET#44]
Version 4.2.0 is published as DEBUG build, instead of RELEASE.

![grafik](https://user-images.githubusercontent.com/5755834/118461457-fcd91b80-b6fd-11eb-93eb-3f2338973e40.png)

**Comment by StingyJack** [comment]
When this is switched to Release, strongly consider embedding the PDB's

**Comment by shatl** [comment]
SourceLink is better alternative to embedding pdb https://github.com/dotnet/sourcelink

**Comment by gfoidl** [comment]
SourceLink is quite orthogonal to debug symbols (pdbs). I agree with @StingyJack that pdbs should be embedded (nowadays). It's mainly for good and thorough diagnostics.

**Comment by totpero** [comment]
Hi @gfoidl check last release v4.3.0
