### ISSUE TITLE
Version in system runtime only uses int32 what happens when you have a version number larger than int32? Exception

### ISSUE THREAD

**Issue by markatosi** [totpero/DeviceDetector.NET#5]
Try with the following user agent string. Notice that the build number is much larger than an int.

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.**1529614902747** Safari/537.36

The Version comparison routine available from the system runtime for this type of comparison as it's far too rigid for the flexible nature of versioning within agent strings.

**Comment by markatosi** [comment]
You might want to look into this
https://github.com/maxhauser/semver

**Comment by totpero** [comment]
Thanks, I will test it.

**Comment by totpero** [comment]
Hi @markatosi , last release 4.3.0 include the  semver nuget. Thanks 👍
