### ISSUE TITLE
Package 4.2.0 contains tests

### ISSUE THREAD

**Issue by shustrenko** [totpero/DeviceDetector.NET#50]
Hi, we added DeviceDetectorNET 4.3 to our project and this is what the memory profiler show us
![image](https://user-images.githubusercontent.com/28841791/139944745-4f8dfd43-7897-4197-a2bd-f685c1108454.png)

Sample of instance
![image](https://user-images.githubusercontent.com/28841791/139944801-9c992eb8-3b2c-45fc-9fd2-2165de1e80f0.png)

**Comment by totpero** [comment]
Hi @shustrenko, 

I just release new version [v6.1.0](https://github.com/totpero/DeviceDetector.NET/releases/tag/v6.1.0)
