### ISSUE TITLE
Updating regexes from the PHP project now produces runtime errors

### ISSUE THREAD

**Issue by echodreamz** [totpero/DeviceDetector.NET#51]
The latest yml files from the PHP project now include a versions property in the oss.yml file.

`
#webOS

regex: '(?:Web0S; .*WEBOS|webOS|web0S|Palm webOS|hpwOS)(?:[/]?(\d+[.\d]+))?'
name: 'webOS'
version: '$1'
versions:
regex: 'WEBOS(\d+[.\d]+)'
version: '$1'
regex: 'Web0S; Linux/SmartTV.+Chrome/68'
version: '5'
regex: 'Web0S; Linux/SmartTV.+Chrome/53'
`
This causes runtime errors stating that Class.Os does not contain a "versions" property. To get around this, I simply added...

`[YamlMember(Alias = "versions")] public Os[] Versions { get; set; }`

And the runtime error goes away, though, this is definitely not the correct fix.

**Comment by sanchezzzhak** [comment]
https://github.com/matomo-org/device-detector/releases/tag/5.0.0

**Comment by totpero** [comment]
#54

**Comment by totpero** [comment]
Hi @echodreamz , @sanchezzzhak , @fpl1976 ,

I just release new version [v6.1.0](https://github.com/totpero/DeviceDetector.NET/releases/tag/v6.1.0),  check this version.

Thanks 👍
