### ISSUE TITLE
Using System.Text.Json

### ISSUE THREAD

**Issue by mshevroja** [totpero/DeviceDetector.NET#58]
For a better performance and less dependency use System.Text.Json instead of Newtonsoft

**Comment by totpero** [comment]
Start from here: https://github.com/totpero/DeviceDetector.NET/commit/56b75566c32ca09e70029e71055711ed6678e826

**Comment by seriouz** [comment]
Isn't there a nuget which I can use?

**Comment by totpero** [comment]
Hi @seriouz for the moment this feature is in dev. Is nit finished yet.

**Comment by totpero** [comment]
Hi @seriouz , @mshevroja 
I have implemented this in https://github.com/totpero/DeviceDetector.NET/releases/tag/v6.4.1 release
Thanks
