### ISSUE TITLE
The example for bot detection is incorrect

### ISSUE THREAD

**Issue by yarong-lifemap** [totpero/DeviceDetector.NET#59]
In the example on the main page of this repository and in Nuget, it's stated that (result != null) means it's a bot. Actually, it's now result.Success that returns this value.

**Comment by totpero** [comment]
Hi @yarong-lifemap ,
I just release new version [v6.1.0](https://github.com/totpero/DeviceDetector.NET/releases/tag/v6.1.0) check if is ok for you.

Thanks 👍
