### ISSUE TITLE
Thread safe

### ISSUE THREAD

**Issue by markatosi** [totpero/DeviceDetector.NET#6]
Currently the Dictionary cache is not thread safe. You can replace the current code with the following to correct

`using System;
using System.Collections.Concurrent;
using System.Collections.Generic;

namespace DeviceDetectorNET.Cache
{
    public class DictionaryCache : ICache
    {
     	private static readonly Object LockObj = new Object();
        private static ConcurrentDictionary<string,object> _staticCache = new       ConcurrentDictionary<string, object>();
        public bool Contains(string id)
        {
            return _staticCache !=null && _staticCache.Keys.Count > 0 && _staticCache.ContainsKey(id);
        }
	public bool Delete(string id)
        {
                object obj;
                _staticCache.TryRemove(id, out obj);
                return true;
        }

	public object Fetch(string id)
        {
            return Contains(id) ? _staticCache[id] : null;
        }

	public bool FlushAll()
        {
            _staticCache = new ConcurrentDictionary<string, object>();
            return true;
        }

	public bool Save(string id, object data, int lifeTime = 0)
        {

                if (Contains(id))
                {
                    _staticCache[id] = data;
                }
                else
                {
                    _staticCache.TryAdd(id, data);
                }
                return true;

        }
    }
}`

**Comment by totpero** [comment]
Ok, Thanks! 👍

**Comment by markatosi** [comment]
You don't need the LockObj code I forgot to remove it after I had tested just using a regular dictionary and decided to use ConcurrentDictionary instead

**Comment by hugoqribeiro** [comment]
I am having this same exact problem with DeviceDetector.NET.NetCore 3.9.2.2.
I did replace it with my own cache implementation but the problem it that the default DictionaryCache is still be instantiated in the DeviceDetector constructor.
Any update on that package?

**Comment by hugoqribeiro** [comment]
Hi. Any news regarding this?

**Comment by totpero** [comment]
Hi,
The .NetCore repo is fork from this repo, is not maintained from us. 
Here is one pull request to port this library to core but is some issues if i do this: [here](https://github.com/totpero/DeviceDetector.NET/pull/3)

**Comment by hugoqribeiro** [comment]
Thank you.

**Comment by totpero** [comment]
Hi @hugoqribeiro, this library now is also supported .net core if you want to use it.
