### ISSUE TITLE
How often is the list of detected devices updated?

### ISSUE THREAD

**Issue by natiki** [totpero/DeviceDetector.NET#7]
Hi,

Looking for a good device detection library and came across this. Just want to know how "fresh" the UA strings are that are managed?

**Comment by totpero** [comment]
you can download the lasts yml regex from [original site](https://github.com/matomo-org/device-detector/tree/master/regexes) and replace them in your project

**Comment by natiki** [comment]
@totpero Stupid question I guess but how do I replace the yml? From what I can see it is included inside the NuGet package and there is no way to supply this via DeviceDetector? Or are you suggesting I clone the repo and maintain my own copy? (not my preference)

**Comment by totpero** [comment]
I will try to update the yml files more often or anyone can create pull request and i will merge it into this repo and we can contribute to this.
I will try to implement the requests and after i will update the repo  when the original php repo will update.

**Comment by totpero** [comment]
Hi @natiki @guibranco I just release new update.
https://github.com/totpero/DeviceDetector.NET/issues/4#issuecomment-435707509
Thanks
