### ISSUE TITLE
User-Agent string changed in Chrome causing undetectable device

### ISSUE THREAD

**Issue by marcelo-qrplus** [totpero/DeviceDetector.NET#71]
Since Octuber-2022, Chrome has been reducing User-Agent string and now on May-2023 change it dramaticaly, causing undetectable device using this lib.

Source: https://developer.chrome.com/blog/user-agent-reduction-oct-2022-updates/

I will try to fix, but if anyone already know this lib and can do it faster, it would be great.

Tks,
MC

**Comment by totpero** [comment]
Hi @marcelo-qrplus 
We already have implemented User Agent Client Hint.
Try to do something like this to set the CH from your request into your code:

```
DeviceDetector.SetVersionTruncation(VersionTruncation.VERSION_TRUNCATION_NONE);

ar userAgent = Request.Headers["User-Agent"]; // change this to the useragent you want to parse
var clientHints = ClientHints.Factory(headers);  // client hints are optional

var dd = new DeviceDetector(userAgent,clientHints);
```

**Comment by marcelo-qrplus** [comment]
Nice tip!! Worked...sorry, I didn't know that!!
Tks @totpero
