### ISSUE TITLE
Incorrect device model

### ISSUE THREAD

**Issue by engahmedtaha** [totpero/DeviceDetector.NET#72]
Mozilla/5.0 (Linux; Android 4.4.2; HTC Desire 820G PLUS dual sim Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36 Instagram 122.0.0.29.238 Android (19/4.4.2; 320dpi; 720x1184; HTC/htc; HTC Desire 820G PLUS dual sim; htc_a50mgp_dug; mt6592; en_US; 187682682)

{
    "ua": "Mozilla\/5.0 (Linux; Android 4.4.2; HTC Desire 820G PLUS dual sim Build\/KOT49H) AppleWebKit\/537.36 (KHTML, like Gecko) Version\/4.0 Chrome\/30.0.0.0 Mobile Safari\/537.36 Instagram 122.0.0.29.238 Android (19\/4.4.2; 320dpi; 720x1184; HTC\/htc; HTC Desire 820G PLUS dual sim; htc_a50mgp_dug; mt6592; en_US; 187682682)",
    "type": "mobile-browser",
    "brand": "HTC",
    "name": "Desire 820G+ dual sim",
    "url": "http:\/\/meta.com\/",
    "os": {
        "name": "Android 4.4 KitKat",
        "code": "android_4_4",
        "url": "https:\/\/en.wikipedia.org\/wiki\/Android_%28operating_system%29",
        "family": "Android",
        "family_code": "android",
        "family_vendor": "Google Inc.",
        "icon": "https:\/\/assets.userstack.com\/icon\/os\/android.png",
        "icon_large": "https:\/\/assets.userstack.com\/icon\/os\/android_big.png"
    },
    "device": {
        "is_mobile_device": true,
        "type": "smartphone",
        "brand": "HTC",
        "brand_code": "htc",
        "brand_url": "http:\/\/www.htc.com\/",
        "name": "Desire 820G+ dual sim"
    },
    "browser": {
        "name": "Instagram App",
        "version": "122.0.0.29.238",
        "version_major": "122",
        "engine": "WebKit\/Blink"
    },
    "crawler": {
        "is_crawler": false,
        "category": null,
        "last_seen": null
    }
}

**Comment by totpero** [comment]
Hi @engahmedtaha ,
I just release new version and look like your UA result and DeviceDetector.NET result is the same.
Can you update to the last version and try again to see if this is fixed?
Thanks
