### ISSUE TITLE
Package DeviceDetector.NET.NetCore 3.9.2.2 is not compatible with net60 (.NETFramework,Version=v6.0)

### ISSUE THREAD

**Issue by Tusharsp** [totpero/DeviceDetector.NET#73]
We are trying to build the code using Azure CI CD but build pipeline is failing with below error.

##[error]The nuget command failed with exit code(1) and error(NU1202: Package DeviceDetector.NET.NetCore 3.9.2.2 is not compatible with net60 (.NETFramework,Version=v6.0). Package DeviceDetector.NET.NetCore 3.9.2.2 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)

Any idea if there is any latest version which supports .NET 6.0?

**Comment by totpero** [comment]
Hi @Tusharsp,
I will add also .net6 compatibility and I will create new release

**Comment by Tusharsp** [comment]
Hi @totpero  -- I see you have mentioned that new release will be created but I also see a "wontfix" label. Kindly confirm if this will get fixed. We really need it to work.

**Comment by totpero** [comment]
Hi @Tusharsp ,
The nuget you have mentioned "DeviceDetector.NET.NetCore" is not from this official repo.
Try to install this one: [DeviceDetector.NET](https://www.nuget.org/packages/DeviceDetector.NET).
I also add new target frameworks and I will create new release after I update to the last 6.1.4 version.

**Comment by totpero** [comment]
Hi @Tusharsp ,
I just create new release with [6.1.4 version](https://www.nuget.org/packages/DeviceDetector.NET/6.1.4). In this version I also add `netstandard2.0;Net462;net5.0;net6.0;net7.0` targets frameworks. You can update to the last nuget version to see if fix your problem.

**Comment by Tusharsp** [comment]
Thank you for the quick action. We will check if we can move from DeviceDetector.NET.NetCore to DeviceDetector.NET. 
Please note that I commented here because in [Nuget page](https://www.nuget.org/packages/DeviceDetector.NET.NetCore) of DeviceDetector.NET.NetCore, the "Project Website" link directs to this page. 

Thanks again. It will take some time for us to get approval to change to this package. Let me know if I should close this issue.

**Comment by totpero** [comment]
DeviceDetector.NET.NetCore is fork from old version of this repo. 
Now DeviceDetector.NET is also compatible with .net core versions.
 Thanks for using this library, I will close this issue and if you have other issues or this issue still persist feel free to reopen. 
👍
