### ISSUE TITLE
Why version for NET 6.0 requires Logging in version 7.0 

### ISSUE THREAD

**Issue by TeemoRawr** [totpero/DeviceDetector.NET#75]
Hi,

why version for NET 6.0 requires version Microsoft.Extensions.Logging.Abstractions in version 7.0

To be honest I think that can be problematic if some big prjects use default build-in package which is version 6.* and it requires version 7? Is it somehow related to features which are in version 7 or is it mistake?

**Comment by totpero** [comment]
Hi @TeemoRawr,
I see that the 7 logging nuget works with .net6 framework version:

https://www.nuget.org/packages/Microsoft.Extensions.Logging.Abstractions/

**Comment by TeemoRawr** [comment]
Ok, but generally if someone use NET 6 and want to use this package then he HAVE to update Microsoft.Extensions.Logging.Abstractions to version 7 for no reason which in big corporate project is sometime impossible (this is my currently problem)

**Comment by totpero** [comment]
Hi @TeemoRawr ,
I fix this in[ 6.2.0](https://www.nuget.org/packages/DeviceDetector.NET/6.2.0) release
You can update to the last version and this will be solved.
