### ISSUE TITLE
Invalid Device and Brand Name

### ISSUE THREAD

**Issue by mymintin** [totpero/DeviceDetector.NET#76]
User Agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.24 (KHTML, like Gecko) Chrome/89.0.4389.116 Safari/534.24 XiaoMi/MiuiBrowser/17.0.20 swan-mibrowser

Result:
Device : desktop
Brand : 
Brand Name : 
Model : 

OS Name : GNU/Linux
OS Short Name : LIN
OS Version : 
OS Platform : x64

Client Type : browser
Client Name : MIUI Browser
Client Version : 17.0.20
Client Short Name : MU
Client Engine : WebKit
Client Engine Version : 534.24

**Comment by totpero** [comment]
Hi @mymintin 

I have test this User Agent online:

[iehol.sse.codesandbox.io](https://iehol.sse.codesandbox.io/#Mozilla/5.0%20(X11;%20Linux%20x86_64)%20AppleWebKit/534.24%20(KHTML,%20like%20Gecko)%20Chrome/89.0.4389.116%20Safari/534.24%20XiaoMi/MiuiBrowser/17.0.20%20swan-mibrowser) 
```
device: {
    id: "",
    type: "desktop",
    brand: "",
    model: ""
}
```

or:
[devicedetector.lw1.at](https://devicedetector.lw1.at/Mozilla%2F5.0%20(X11;%20Linux%20x86_64)%20AppleWebKit%2F534.24%20(KHTML,%20like%20Gecko)%20Chrome%2F89.0.4389.116%20Safari%2F534.24%20XiaoMi%2FMiuiBrowser%2F17.0.20%20swan-mibrowser
)
 ```
 "deviceName": "desktop",
  "deviceBrand": {
    "name": "",
    "short_name": ""
  },
```
and the result is the same like in DeviceDetector.Net

If the expected result need to be other, you need to write this issue to the original php repo: https://github.com/matomo-org/device-detector and after this will be fixed there, I will update the regexes also here.

Thanks 👍
