### ISSUE TITLE
What is the expected way to detect if a device is a tablet?

### ISSUE THREAD

**Issue by natiki** [totpero/DeviceDetector.NET#8]
Hi,

There is no IsTablet() method ;-). Is there also a definition of device?

```c#
    /// <summary>Holds the device type after parsing the UA</summary>
    protected int? device;
```

because then I could probably figure out what to change from the IsMobile() implementation to add this as a method.

Cheers,

**Comment by Calx-Takeno** [comment]
I want the IsTablet() methed too.

**Comment by totpero** [comment]
HI @natiki @Calx-Takeno i have add IsTablet() method but i'm not 100% sure is all the validations. In the orginal php repo is only IsMobile() method. but you can try my IsTablet() method and see if works.
Thanks.

**Comment by Calx-Takeno** [comment]
> HI @natiki @Calx-Takeno i have add IsTablet() method but i'm not 100% sure is all the validations. In the orginal php repo is only IsMobile() method. but you can try my IsTablet() method and see if works.
> Thanks.

Thank you very much. That's great!
