### ISSUE TITLE
Exception parsing operating systems.

### ISSUE THREAD

**Issue by xramcire** [totpero/DeviceDetector.NET#84]
The given key '8' was not present in the dictionary.

System.Collections.Generic.KeyNotFoundException:
   at System.ThrowHelper.ThrowKeyNotFoundException (System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Collections.Generic.Dictionary`2.get_Item (System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at DeviceDetectorNET.Parser.OperatingSystemParser.Parse (DeviceDetector.NET, Version=6.3.3.0, Culture=neutral, PublicKeyToken=null)
   at DeviceDetectorNET.DeviceDetector.Parse (DeviceDetector.NET, Version=6.3.3.0, Culture=neutral, PublicKeyToken=null)
   
   I am unable to locate the UserAgent in question.

**Comment by totpero** [comment]
Hi @xramcire , can you provide sample code?

**Comment by xramcire** [comment]
`        private bool IsMobile()
        {
            try
            {
                var headers = _httpContextAccessor.HttpContext?.Request.Headers;

                if (headers is null)
                {
                    return false;
                }

                var userAgent = headers.UserAgent;
                var headerDictionary = headers.ToDictionary(a => a.Key, a => a.Value.ToArray().FirstOrDefault());
                var clientHints = ClientHints.Factory(headerDictionary);

                var dd = new DeviceDetector(userAgent, clientHints);
                dd.DiscardBotInformation();
                dd.Parse();
                return dd.IsMobile();
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "{method} failed.", nameof(IsMobile));
                return false;
            }
        }`

**Comment by xramcire** [comment]
I'm adding code to my stack to collect the user agent causing the error but it will be a couple weeks before it gets into production and the right user sends the request.

**Comment by xramcire** [comment]
I believe it is referring to this dictionary.

                if ("Fire OS" == text)
                {
                    string key = ((text2.Split('.').Length != 0) ? text2.Split('.')[0] : "0");
                    Dictionary<string, string> dictionary = new Dictionary<string, string>
                    {
                        { "11", "8" },
                        { "10", "8" },
                        { "9", "7" },
                        { "7", "6" },
                        { "5", "5" },
                        { "4.4.3", "4.5.1" },
                        { "4.4.2", "4" },
                        { "4.2.2", "3" },
                        { "4.0.3", "3" },
                        { "4.0.2", "3" },
                        { "4", "2" },
                        { "2", "1" }
                    };
                    text2 = dictionary[text2] ?? dictionary[key] ?? text2;
                }
            }

**Comment by liviuconcioiu** [comment]
There's no `Fire OS` version based on `Android 8`.

https://developer.amazon.com/docs/fire-tv/fire-os-overview.html

**Comment by liviuconcioiu** [comment]
I know where the bug is, and is also upstream. Some client hints, don't report the Android version, and we get it from user agent, which is `8` in this case, then it tries to check again for version 8 in the array.

Here is the issues:

https://github.com/totpero/DeviceDetector.NET/blob/f2106bb85c077328b8441773d7fb49cb1b220c93/DeviceDetector.NET/Parser/OperatingSystemParser.cs#L373-L376

**Comment by liviuconcioiu** [comment]
https://github.com/totpero/DeviceDetector.NET/blob/master/DeviceDetector.NET/Parser/OperatingSystemParser.cs#L392

This should fix the problem:

`if ("Fire OS" == name && !string.IsNullOrEmpty(osFromClientHints.Version))`

**Comment by totpero** [comment]
Thank @liviuconcioiu for your  contribution.
I will update the .net version to last php version 🙏 thanks

**Comment by xramcire** [comment]
Thanks for the fix!
