### ISSUE TITLE
Problem with client hints?

### ISSUE THREAD

**Issue by hugoqribeiro** [totpero/DeviceDetector.NET#88]
Hi.

Since upgrading to version 6.4.1, the detection for Chrome seems to have an issue if client hints are passed.

This user-agent:

`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36`

Without client hints it resolves to the following browser:

- Name: Chrome
- Version: 131.0.0.0
- Engine: Blink

If then, we also pass the following client hint, as sent by Chrome:

`sec-ch-ua = "Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"`

The resulting browser is wrong:

- Name: 360 Secure Browser
- Version: 131.0.0.0
- Engine: Blink

**Comment by liviuconcioiu** [comment]
@hugoqribeiro can you test with the changed I've done in my PR and see if it works?

**Comment by totpero** [comment]
Hi @hugoqribeiro , something didn't pass

**Comment by liviuconcioiu** [comment]
@totpero I made another PR. I think the tests were wrong. Feel free to make changes, but what it is in tests should be expected from detection. Is my first time coding in C#.
